services:
  - type: web
    name: psau-admission-system
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: DB_HOST
        value: 34.170.34.174
      - key: DB_NAME
        value: psau_admission
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: Psau_2025
      - key: DB_PORT
        value: 3306
      - key: FIREBASE_API_KEY
        value: AIzaSyBQ5jLQX2JggHQU0ikymEEjywxEos5Lr3c
      - key: FIREBASE_AUTH_DOMAIN
        value: psau-admission-system-f55f8.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: psau-admission-system-f55f8
      - key: FIREBASE_STORAGE_BUCKET
        value: psau-admission-system-f55f8.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "615441800587"
      - key: FIREBASE_APP_ID
        value: 1:615441800587:web:8b0df9b012e24c147da38e
      - key: FIREBASE_EMAIL_FUNCTION_URL
        value: https://us-central1-psau-admission-system-f55f8.cloudfunctions.net/sendEmail
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: "true"
